### Import the required modules

In [146]:
import glob # helps in selecting files
import pandas as pd # helps in processing CSV files
from datetime import datetime # helps in working with dates and times

### Define necessary file names

In [147]:
logfile = "logfile.txt" # log file
loadfile = "WorldCups_CompleteSummary.csv" # final target data file

### Function to read csv file

In [148]:
def extract_from_csv(file):
    dataframe = pd.read_csv(file)
    return dataframe

### Function to read json file

In [149]:
def extract_from_json(file):
    dataframe = pd.read_json(file)
    return dataframe

### Create a list with the names of the columns

In [150]:
List_columns=['Year', 'Country', 'Winner', 'Runners-Up', 'Third', 'Fourth', 'GoalsScored', 'QualifiedTeams', 'MatchesPlayed', 'Attendance']

### extract function to extract data from available csv and json files in the working directory

In [151]:
def extract():
    extracted_data = pd.DataFrame(columns=List_columns)
        
    for jsonfile in glob.glob("*.json"):
        extracted_data = extracted_data.append(extract_from_json(jsonfile), ignore_index=True)
    
    for csvfile in glob.glob("*.csv"):
        extracted_data = extracted_data.append(extract_from_csv(csvfile), ignore_index=True)
 
    extracted_data.sort_values(by=["Year"], inplace=True)
    return extracted_data
#extract()

### transform function to perform the desired operation. In this example, a new column with title "GoalsScoredPerMatch" has been created.

In [152]:
def transform(extracted_data_file):
    extracted_data_file["GoalsScoredPerMatch"] = (extracted_data_file.GoalsScored/extracted_data_file.MatchesPlayed).astype(float).round(2)
    return extracted_data_file

### load function to load the transformed data into the target file

In [153]:
def load(data_to_load, loadfile):
    data_to_load.to_csv(loadfile, index=False)

### log function to keep track of process timings

In [154]:
def log(message):
    timestamp_format = "%H:%M:%S-%d:%h:%Y"
    Current_time = datetime.now()
    Timestamp = Current_time.strftime(timestamp_format)
    with open(logfile,"a") as f:
        f.write(Timestamp + ',' + message + '\n')

# Execution of ETL Process

In [155]:
log("Beginning of ETL process")

### Step1: Extract Process

In [156]:
log("Beginning of Extract phase")
extracted_data = extract()
log("End of Extract phase")
#extracted_data

### Step2: Transform Process

In [157]:
log("Beginning of Transform phase")
transformed_data = transform(extracted_data)
log("End of Transform phase")
#transformed_data

### Step3: Load Process

In [158]:
log("Beginning of Load phase")
load(transformed_data, loadfile)
log("End of Load phase")

In [159]:
log("End of ETL process")

In [161]:
# Final saved csv file
df = pd.read_csv(loadfile)
df

,Year,Country,Winner,Runners-Up,Third,Fourth,GoalsScored,QualifiedTeams,MatchesPlayed,Attendance,GoalsScoredPerMatch
0,1930,Uruguay,Uruguay,Argentina,USA,Yugoslavia,70,13,18,590.549,3.89
1,1934,Italy,Italy,Czechoslovakia,Germany,Austria,70,16,17,363.000,4.12
2,1938,France,Italy,Hungary,Brazil,Sweden,84,15,18,375.700,4.67
3,1950,Brazil,Uruguay,Brazil,Sweden,Spain,88,13,22,1.045.246,4.00
4,1954,Switzerland,Germany FR,Hungary,Austria,Uruguay,140,16,26,768.607,5.38
5,1958,Sweden,Brazil,Sweden,France,Germany FR,126,16,35,819.810,3.60
6,1962,Chile,Brazil,Czechoslovakia,Chile,Yugoslavia,89,16,32,893.172,2.78
7,1966,England,England,Germany FR,Portugal,Soviet Union,89,16,32,1.563.135,2.78
8,1970,Mexico,Brazil,Italy,Germany FR,Uruguay,95,16,32,1.603.975,2.97
9,1974,Germany,Germany FR,Netherlands,Poland,Brazil,97,16,38,1.865.753,2.55
10,1978,Argentina,Argentina,Netherlands,Brazil,Italy,102,16,38,1.545.791,2.68
11,1982,Spain,Italy,Germany FR,Poland,France,146,24,52,2.109.723,2.81
12,1986,Mexico,Argentina,Germany FR,France,Belgium,132,24,52,2.394.031,2.54
13,1990,Italy,Germany FR,Argentina,Italy,England,115,24,52,2.516.215,2.21
14,1994,USA,Brazil,Italy,Sweden,Bulgaria,141,24,52,3.587.538,2.71
15,1998,France,France,Brazil,Croatia,Netherlands,171,32,64,2.785.100,2.67
16,2002,Korea/Japan,Brazil,Germany,Turkey,Korea Republic,161,32,64,2.705.197,2.52
17,2006,Germany,Italy,France,Germany,Portugal,147,32,64,3.359.439,2.30
18,2010,South Africa,Spain,Netherlands,Germany,Uruguay,145,32,64,3.178.856,2.27
19,2014,Brazil,Germany,Argentina,Netherlands,Brazil,171,32,64,3.386.810,2.67